variable "namespace" {}
variable "aws_instance_ami" {}
variable "aws_instance_type" {}
variable "ssh_key_name" {}
variable "owner" {}
variable "ttl" {}
variable "user_data" {}
variable "subnet_id" {}
variable "vpc_security_group_ids" {}
variable "route53_zone_id" {}
variable "route53_zone_name" {}
